import type { Metadata } from "next"
import { FileText } from "lucide-react"

export const metadata: Metadata = {
  title: "Terms & Conditions - Rules of Using InstaBioGen",
  description:
    "Read the terms and conditions for using InstaBioGen. Understand your rights and obligations as a user.",
  alternates: {
    canonical: "https://profilebiogenerator.site/terms-and-conditions",
  },
  openGraph: {
    title: "Terms & Conditions | InstaBioGen",
    description: "Read the terms and conditions for using InstaBioGen.",
    url: "https://profilebiogenerator.site/terms-and-conditions",
    type: "website",
  },
  twitter: {
    card: "summary",
    title: "Terms & Conditions | InstaBioGen",
    description: "Read the terms and conditions.",
  },
}

const sections = [
  {
    title: "1. Acceptance of Terms",
    content:
      "By accessing, browsing, or using InstaBioGen (profilebiogenerator.site), you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions, along with our Privacy Policy and Disclaimer. If you do not agree to any part of these terms, you must discontinue use of our website immediately. These terms apply to all visitors, users, and anyone who accesses the website.",
  },
  {
    title: "2. Description of Service",
    content:
      "InstaBioGen provides a free, AI-powered Instagram bio generator tool that helps users create creative, unique, and personalized bios for their Instagram profiles. Our service includes:",
    list: [
      "An interactive bio generator with multiple tones (attitude, cool, stylish, VIP, swag, motivational, etc.) and categories.",
      "One-click copy functionality for generated bios.",
      "Customization options including emoji and hashtag toggles.",
      "A blog section with tips, guides, and inspiration related to Instagram bios.",
      "Educational content about crafting effective social media profiles.",
    ],
  },
  {
    title: "3. Eligibility",
    content:
      "You must be at least 13 years of age to use InstaBioGen. By using our website, you represent and warrant that you meet this age requirement. If you are under 18, you should use this website under the supervision of a parent or legal guardian.",
  },
  {
    title: "4. User Responsibilities",
    content:
      "As a user of InstaBioGen, you agree to the following responsibilities:",
    list: [
      "You will not use the tool to generate bios that are harmful, offensive, threatening, abusive, harassing, defamatory, or otherwise objectionable.",
      "You are solely responsible for the bios you choose to use on your social media profiles. We provide suggestions; how you use them is your decision.",
      "You will not attempt to disrupt, damage, hack, or interfere with our website, servers, or services in any way.",
      "You will not use automated scripts, bots, or tools to scrape, copy, or mass-download content from our website.",
      "You will not redistribute, republish, or sell content from our website for commercial purposes without explicit written permission.",
      "You will comply with all applicable local, state, national, and international laws while using our service.",
    ],
  },
  {
    title: "5. Intellectual Property Rights",
    content:
      "The website design, source code, graphics, logos, icons, and original written content (including blog posts) on InstaBioGen are owned by us and protected by intellectual property laws. You may NOT copy, modify, distribute, or create derivative works from our website design or code without permission.",
    afterContent:
      "Regarding generated bios: The bios created by our tool are provided for your personal use. You are free to use any generated bio on your social media profiles, personal projects, or non-commercial purposes. However, you may not compile or redistribute large collections of generated bios for commercial purposes.",
  },
  {
    title: "6. Generated Content",
    content:
      "Content generated by InstaBioGen is created algorithmically. We do not guarantee that generated content is:",
    list: [
      "Completely original or free from similarities with existing content elsewhere on the internet.",
      "Suitable for all audiences, platforms, or contexts.",
      "Compliant with Instagram's Terms of Service or Community Guidelines at all times.",
      "Free from typographical, grammatical, or contextual errors.",
    ],
    afterContent:
      "You agree to review all generated bios before use and accept full responsibility for content you publish on your profiles.",
  },
  {
    title: "7. Availability of Service",
    content:
      "We strive to keep InstaBioGen available 24/7, but we do not guarantee uninterrupted access to our service. The website may be temporarily unavailable due to maintenance, updates, server issues, or circumstances beyond our control. We reserve the right to modify, suspend, or discontinue any part of the service at any time without prior notice.",
  },
  {
    title: "8. Limitation of Liability",
    content:
      "To the maximum extent permitted by law, InstaBioGen, its owners, operators, and contributors shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use our website or service. This includes but is not limited to damages for loss of profits, data, goodwill, or other intangible losses, even if we have been advised of the possibility of such damages.",
  },
  {
    title: "9. Indemnification",
    content:
      "You agree to indemnify, defend, and hold harmless InstaBioGen and its creators from any claims, liabilities, damages, losses, and expenses (including legal fees) arising from your use of our website, violation of these terms, or infringement of any third-party rights.",
  },
  {
    title: "10. Links to Third-Party Websites",
    content:
      "Our website may contain links to third-party websites or services. These links are provided for convenience only. We do not control and are not responsible for the content, privacy policies, or practices of any third-party sites. Visiting external links is at your own risk.",
  },
  {
    title: "11. Modifications to Terms",
    content:
      "We reserve the right to update, change, or modify these Terms and Conditions at any time. Changes will be posted on this page with an updated revision date. Your continued use of InstaBioGen after any modifications constitutes acceptance of the new terms. We encourage you to review this page regularly.",
  },
  {
    title: "12. Severability",
    content:
      "If any provision of these Terms and Conditions is found to be invalid, illegal, or unenforceable by a court of competent jurisdiction, the remaining provisions shall continue in full force and effect.",
  },
  {
    title: "13. Governing Law",
    content:
      "These Terms and Conditions shall be governed by and construed in accordance with the laws of India. Any disputes arising from or relating to these terms or your use of InstaBioGen shall be subject to the exclusive jurisdiction of the courts located in India.",
  },
  {
    title: "14. Contact Information",
    content:
      "If you have any questions, concerns, or feedback about these Terms and Conditions, you can reach us at:",
    afterContent: "Email: contact@profilebiogenerator.site",
  },
]

export default function TermsPage() {
  return (
    <>
      {/* Hero */}
      <section className="relative overflow-hidden bg-background py-16 lg:py-24">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,var(--tw-gradient-stops))] from-primary/5 via-transparent to-transparent" />
        <div className="relative mx-auto max-w-3xl px-4 lg:px-8">
          <div className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-1.5 text-sm font-medium text-primary">
            <FileText className="h-3.5 w-3.5" />
            Legal Agreement
          </div>
          <h1
            className="mt-6 text-4xl font-bold tracking-tight text-foreground md:text-5xl"
            style={{ fontFamily: "var(--font-heading)" }}
          >
            Terms &amp; Conditions
          </h1>
          <p className="mt-4 text-lg text-muted-foreground">
            Last updated: February 2026
          </p>
          <p className="mt-2 leading-relaxed text-muted-foreground">
            These terms govern your use of InstaBioGen. Please read them
            carefully. By continuing to use our website, you accept these terms
            in full.
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="border-t border-border bg-card py-16 lg:py-20">
        <div className="mx-auto max-w-3xl px-4 lg:px-8">
          <div className="flex flex-col gap-10">
            {sections.map((section) => (
              <div
                key={section.title}
                className="rounded-2xl border border-border bg-background p-6 md:p-8"
              >
                <h2 className="text-xl font-bold text-foreground">
                  {section.title}
                </h2>
                {section.content && (
                  <p className="mt-3 leading-relaxed text-muted-foreground">
                    {section.content}
                  </p>
                )}
                {section.list && (
                  <ul className="mt-4 flex flex-col gap-2 pl-1">
                    {section.list.map((item) => (
                      <li key={item} className="flex items-start gap-2">
                        <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                        <p className="text-sm leading-relaxed text-muted-foreground">
                          {item}
                        </p>
                      </li>
                    ))}
                  </ul>
                )}
                {section.afterContent && (
                  <p className="mt-4 text-sm font-medium text-foreground">
                    {section.afterContent}
                  </p>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  )
}
