import { Metadata } from "next"
import { BioGeneratorTool } from "@/components/bio-generator-tool"

export const metadata: Metadata = {
  title: "Instagram Bio Generator – Create Unique Bios Instantly",
  description:
    "Discover the best instagram bio ideas and generate stunning, high-converting bios in seconds. Free AI-powered tool for aesthetic, stylish, and professional profiles.",
  alternates: {
    canonical: "/",
  },
}

export default function HomePage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebSite",
            name: "InstaBioGen",
            url: "https://profilebiogenerator.site/",
            potentialAction: {
              "@type": "SearchAction",
              target: "https://profilebiogenerator.site/generator?category={search_term_string}",
              "query-input": "required name=search_term_string",
            },
          }),
        }}
      />

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            mainEntity: [
              {
                "@type": "Question",
                name: "What is an Instagram bio maker and how does it work?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text: "An instagram bio maker is an AI-powered tool that generates unique, stylish, and optimized bios for your Instagram profile. You select a category, choose a tone, and the tool instantly creates multiple ready-to-use bio options tailored to your personality and goals.",
                },
              },
              {
                "@type": "Question",
                name: "Is this Instagram bio generator completely free?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text: "Yes, our tool is 100% free with no hidden charges, no subscriptions, and no sign-up required. You can generate unlimited bios without any restrictions.",
                },
              },
              {
                "@type": "Question",
                name: "Can I use these bios on other platforms?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text: "Absolutely. While optimized for Instagram, the bios generated by our instagram bio maker work perfectly on TikTok, Twitter (X), Facebook, YouTube, and any other social media platform.",
                },
              },
              {
                "@type": "Question",
                name: "How often should I update my Instagram bio?",
                acceptedAnswer: {
                  "@type": "Answer",
                  text: "Social media experts recommend updating your bio every 4-6 weeks. Fresh bios signal activity to the algorithm and keep your profile aligned with current trends and your evolving brand.",
                },
              },
            ],
          }),
        }}
      />

      <main className="mx-auto max-w-5xl px-4 py-16 sm:px-6 lg:px-8 bg-background text-foreground space-y-24">

        {/* ============================================================
            1. HERO SECTION — H1 + INTRO PARAGRAPH + TOOL
        ============================================================ */}
        <section id="generator" className="text-center space-y-8 mt-8">
          <span className="inline-flex items-center rounded-full bg-primary/10 px-4 py-1.5 text-xs font-semibold text-primary">
            🚀 #1 Free AI-Powered Tool
          </span>

          {/* H1 — keyword: "Premium Insta Bio Generator" */}
          <h1 className="text-4xl font-extrabold tracking-tight sm:text-5xl lg:text-6xl text-balance">
            Premium Insta Bio Generator
          </h1>

          {/* INTRO PARAGRAPH — exactly 35 words, keyword "ig bio generator" within first 100 words */}
          <p className="mx-auto max-w-3xl text-lg sm:text-xl text-muted-foreground text-pretty">
            Looking for the perfect Instagram bio? Our ig bio generator crafts unique, aesthetic, and high-converting profile descriptions in seconds. Stand out, attract followers, and make every visitor hit that follow button instantly.
          </p>

          <div className="pt-2">
            <a
              href="#generator-tool"
              className="inline-flex h-14 items-center justify-center rounded-full bg-primary px-8 text-lg font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring"
            >
              Generate Your Bio Now 🚀
            </a>
          </div>

          {/* TOOL SECTION — placeholder as requested */}
          <div id="generator-tool" className="pt-8">
            <BioGeneratorTool />
          </div>
        </section>

        {/* ============================================================
            2. HOW TO USE SECTION
        ============================================================ */}
        <section className="mx-auto max-w-3xl space-y-6">
          <h2 className="text-2xl font-bold tracking-tight sm:text-3xl">How to Use the Instagram Bio Generator</h2>
          <p className="text-lg leading-relaxed text-muted-foreground">
            Creating a standout bio takes just three simple steps. No sign-up, no downloads, and absolutely no design skills required.
          </p>
          <ol className="list-inside list-decimal space-y-4 text-lg text-muted-foreground ml-4">
            <li>
              <strong>Select Your Category:</strong> Choose a niche that matches your profile — personal, business, aesthetic, gamer, travel, or any style you prefer.
            </li>
            <li>
              <strong>Pick Your Tone:</strong> Decide the vibe. Whether you want attitude, professional, funny, cool, or minimalist — the generator adapts to your personality.
            </li>
            <li>
              <strong>Generate and Copy:</strong> Hit the generate button, browse through multiple unique results, and copy the perfect bio directly to your clipboard. Paste it into Instagram and you are done.
            </li>
          </ol>
        </section>

        {/* ============================================================
            3. H2 — "Instagram Bio Ideas"
        ============================================================ */}
        <section className="mx-auto max-w-3xl space-y-6">
          <h2 className="text-2xl font-bold tracking-tight sm:text-3xl">Instagram Bio Ideas</h2>
          <p className="text-lg leading-relaxed text-muted-foreground">
            Your Instagram bio is the first thing visitors see when they land on your profile. It is your digital handshake, your elevator pitch, and your personal brand statement — all compressed into 150 characters. That is exactly why having the right Instagram bio ideas matters more than most people realize.
          </p>
          <p className="text-lg leading-relaxed text-muted-foreground">
            A well-crafted bio immediately communicates who you are, what you do, and why someone should follow you. It sets the tone for your entire account. Whether you are a content creator building an audience, a small business owner driving traffic to your store, or simply someone who wants their profile to look polished and intentional, your bio is the gateway to engagement.
          </p>
          <p className="text-lg leading-relaxed text-muted-foreground">
            Great bio ideas go beyond generic motivational quotes. They leverage strategic formatting, carefully chosen emojis, and concise language that speaks directly to your target audience. A strong bio reduces bounce rates on your profile, increases your follower-to-visitor conversion ratio, and gives the algorithm a positive signal that your account is active and relevant.
          </p>
          <p className="text-lg leading-relaxed text-muted-foreground">
            Think of your bio as a micro-landing page. Every word carries weight. Every line break serves a purpose. The most successful Instagram accounts treat their bios as living documents — updated regularly to reflect seasonal campaigns, new achievements, or shifting personal brands. By investing time into thoughtful bio ideas, you are investing directly into your growth.
          </p>
        </section>

        {/* ============================================================
            4. H2 — "What is Instagram Bio Generator?"
        ============================================================ */}
        <section className="mx-auto max-w-3xl space-y-6">
          <h2 className="text-2xl font-bold tracking-tight sm:text-3xl">What is Instagram Bio Generator?</h2>
          <p className="text-lg leading-relaxed text-muted-foreground">
            An Instagram Bio Generator is an AI-powered online tool designed to help you create professional, stylish, and engaging profile descriptions without any manual brainstorming. Instead of staring at a blank cursor wondering how to summarize your entire personality in a handful of characters, the generator does the creative heavy lifting for you.
          </p>
          <p className="text-lg leading-relaxed text-muted-foreground">
            Our tool analyzes your selected niche, preferred tone, and stylistic preferences to produce multiple unique bio options instantly. It draws from thousands of proven copywriting patterns, trending formats, and high-performing profile structures to deliver results that are not only visually appealing but also psychologically optimized for conversions.
          </p>
          <p className="text-lg leading-relaxed text-muted-foreground">
            Whether you need a minimalist aesthetic bio, a bold attitude statement, a professional brand summary, or a witty one-liner, our generator handles every category with precision. It eliminates creative block entirely and ensures your profile always looks fresh, relevant, and distinctly yours.
          </p>
        </section>

        {/* ============================================================
            5. UNIQUE SECTION — Three Parts
        ============================================================ */}
        <section className="mx-auto max-w-4xl space-y-10">
          <h2 className="text-2xl font-bold tracking-tight sm:text-3xl text-center">Explore Bio Styles for Every Identity</h2>

          {/* a) Aesthetic Instagram Bio Ideas */}
          <div className="bg-card p-8 rounded-2xl border border-border shadow-sm space-y-4">
            <h3 className="text-xl font-bold">🌸 Aesthetic Instagram Bio Ideas</h3>
            <p className="text-lg text-muted-foreground">
              Aesthetic bios are all about creating a mood. They use minimalist formatting, soft symbols, and poetic brevity to evoke mystery and refined taste. A perfectly styled aesthetic bio signals that your content is curated, intentional, and worth following. Think soft pastels in text form — delicate, beautiful, and effortlessly magnetic.
            </p>
          </div>

          {/* b) Instagram Bio for Girls & Boys */}
          <div className="bg-card p-8 rounded-2xl border border-border shadow-sm space-y-4">
            <h3 className="text-xl font-bold">👑 Instagram Bio for Girls &amp; Boys</h3>
            <p className="text-lg text-muted-foreground">
              Your personal bio is your digital first impression. For girls, bios that balance confidence with creativity perform exceptionally well — think bold affirmations paired with aesthetic formatting. For boys, bios that project ambition, humor, or a sharp attitude tend to attract the most engagement. Our generator creates tailored options for both, ensuring your profile feels authentically you.
            </p>
          </div>

          {/* c) Business & Brand Bios */}
          <div className="bg-card p-8 rounded-2xl border border-border shadow-sm space-y-4">
            <h3 className="text-xl font-bold">💼 Business &amp; Brand Bios</h3>
            <p className="text-lg text-muted-foreground">
              For entrepreneurs, startups, and established brands, your Instagram bio is arguably the most important 150 characters of marketing copy you will ever write. It must establish authority, communicate your value proposition clearly, and drive traffic to your link. A strong business bio turns casual browsers into paying customers and brand advocates.
            </p>
          </div>
        </section>

        {/* ============================================================
            6. H2 — "Instagram Bio Maker"
        ============================================================ */}
        <section className="mx-auto max-w-3xl space-y-6">
          <h2 className="text-2xl font-bold tracking-tight sm:text-3xl">Instagram Bio Maker</h2>
          <p className="text-lg leading-relaxed text-muted-foreground">
            An Instagram bio maker is more than a text generator — it is a strategic branding tool built for the modern social media landscape. In an era where attention spans are measured in milliseconds, your profile bio is the single most important piece of copy on your entire account. It determines whether a visitor becomes a follower or bounces away forever.
          </p>
          <p className="text-lg leading-relaxed text-muted-foreground">
            Our bio maker combines advanced AI with proven copywriting principles to produce bios that are not only creative but conversion-focused. Every output is engineered to answer the three questions every profile visitor subconsciously asks: Who is this person? What value do they provide? Why should I follow them right now?
          </p>
          <p className="text-lg leading-relaxed text-muted-foreground">
            The tool supports an extensive range of categories — from aesthetic and attitude to professional, gaming, travel, and beyond. It adapts to trending formats, incorporates strategic emoji placement, and ensures proper line-break formatting so your bio looks perfect when pasted directly into Instagram. No more broken spacing, no more formatting headaches.
          </p>
          <p className="text-lg leading-relaxed text-muted-foreground">
            Whether you are refreshing a stale profile, launching a new brand account, or simply want to test different bio styles, our Instagram bio maker gives you unlimited creative options at zero cost. It is fast, intuitive, and designed to make your profile impossible to scroll past.
          </p>
        </section>

        {/* ============================================================
            7. TIPS SECTION — "Tips to Write Better Bios"
        ============================================================ */}
        <section className="mx-auto max-w-3xl space-y-6">
          <h2 className="text-2xl font-bold tracking-tight sm:text-3xl">Tips to Write Better Bios</h2>
          <p className="text-lg leading-relaxed text-muted-foreground">
            Even with the best tools at your fingertips, understanding the anatomy of a perfect bio gives you a decisive edge. Here are actionable tips to elevate your profile:
          </p>
          <ul className="list-inside list-disc space-y-3 text-lg text-muted-foreground ml-4">
            <li>
              <strong>Lead With a Hook:</strong> Your first line is your headline. State who you are or the value you provide in a way that is impossible to ignore.
            </li>
            <li>
              <strong>Show, Don&apos;t Tell:</strong> Instead of saying &quot;I&apos;m creative,&quot; demonstrate it through your formatting, word choice, and emoji selection.
            </li>
            <li>
              <strong>Use Line Breaks Strategically:</strong> Never write a dense block of text. Break your bio into scannable lines that guide the reader&apos;s eye naturally.
            </li>
            <li>
              <strong>Include a Clear Call-to-Action:</strong> Tell visitors exactly what to do next — click the link, check your latest post, or send a DM.
            </li>
            <li>
              <strong>Keep Emojis Intentional:</strong> Use emojis as visual bullet points or emotional accents, not as decoration. Two to four well-placed emojis outperform a wall of symbols.
            </li>
            <li>
              <strong>Update Regularly:</strong> Refresh your bio every four to six weeks. A current bio signals an active, engaged account to both followers and the algorithm.
            </li>
            <li>
              <strong>Match Your Content:</strong> Your bio should align with the content you actually post. Consistency between bio and feed builds trust and increases follow-through.
            </li>
          </ul>
        </section>

        {/* ============================================================
            8. H3 — "Why Choose Us"
        ============================================================ */}
        <section className="mx-auto max-w-4xl space-y-8">
          <h3 className="text-2xl font-bold tracking-tight text-center sm:text-3xl">Why Choose Us</h3>
          <p className="text-lg leading-relaxed text-muted-foreground text-center max-w-3xl mx-auto">
            In a crowded market of generic bio tools, we stand apart by delivering quality, speed, and genuine value that transforms your social media presence.
          </p>
          <div className="grid sm:grid-cols-2 gap-6">
            <div className="bg-card p-6 rounded-2xl border border-border shadow-sm">
              <h4 className="text-xl font-bold flex items-center gap-2">⚡ Lightning-Fast Results</h4>
              <p className="mt-2 text-muted-foreground">Generate dozens of polished, ready-to-use bios in under three seconds. No waiting, no loading screens — just instant creative output.</p>
            </div>
            <div className="bg-card p-6 rounded-2xl border border-border shadow-sm">
              <h4 className="text-xl font-bold flex items-center gap-2">🧬 100% Unique Outputs</h4>
              <p className="mt-2 text-muted-foreground">Our AI produces fresh, original content every time. No recycled lists, no copy-paste libraries — every bio is dynamically generated for your exact needs.</p>
            </div>
            <div className="bg-card p-6 rounded-2xl border border-border shadow-sm">
              <h4 className="text-xl font-bold flex items-center gap-2">🎯 Conversion-Optimized</h4>
              <p className="mt-2 text-muted-foreground">Every template is crafted using proven copywriting psychology. Your bio will not just look good — it will actively drive follows, clicks, and engagement.</p>
            </div>
            <div className="bg-card p-6 rounded-2xl border border-border shadow-sm">
              <h4 className="text-xl font-bold flex items-center gap-2">🔓 Free Forever</h4>
              <p className="mt-2 text-muted-foreground">No hidden fees, no premium tiers, no sign-up walls. Access the full power of our tool at absolutely zero cost, unlimited times, forever.</p>
            </div>
          </div>
        </section>

        {/* ============================================================
            9. FAQ SECTION — Paragraph style, bold questions, no headings
        ============================================================ */}
        <section className="mx-auto max-w-3xl space-y-8">
          <h2 className="text-2xl font-bold tracking-tight sm:text-3xl">Frequently Asked Questions</h2>

          <div className="space-y-6 text-lg leading-relaxed text-muted-foreground">
            <p>
              <strong>What is an instagram bio maker and how does it work?</strong>{" "}
              An instagram bio maker is an AI-powered tool that generates unique, stylish, and optimized bios for your Instagram profile. You simply select a category that matches your niche, choose a tone that reflects your personality, and the tool instantly creates multiple ready-to-use bio options. There is no sign-up required, no downloads, and no cost involved — just fast, creative results tailored to you.
            </p>

            <p>
              <strong>Is this Instagram bio generator completely free to use?</strong>{" "}
              Yes, our tool is 100% free with no hidden charges, no premium subscriptions, and no email gates. You can generate as many bios as you want, every single day, without ever hitting a paywall. We believe everyone deserves access to professional-grade branding tools regardless of budget.
            </p>

            <p>
              <strong>Can I use bios generated by this instagram bio maker on other social media platforms?</strong>{" "}
              Absolutely. While the formatting and character limits are optimized specifically for Instagram, the bios work beautifully on TikTok, Twitter (X), Facebook, YouTube, and any other platform that features a profile description. Simply copy, paste, and customize as needed for each platform.
            </p>

            <p>
              <strong>How often should I update my Instagram bio for the best results?</strong>{" "}
              Social media experts recommend refreshing your bio every four to six weeks. Regular updates signal to the algorithm and your audience that your account is active and evolving. Using an instagram bio maker like ours makes this effortless — generate a fresh bio in seconds whenever you want to keep your profile current, on-trend, and engaging.
            </p>
          </div>
        </section>

      </main>
    </>
  )
}
