import type { Metadata } from "next"
import { AlertTriangle } from "lucide-react"

export const metadata: Metadata = {
  title: "Disclaimer - Important Legal Information | InstaBioGen",
  description:
    "Read InstaBioGen's disclaimer. Understand the limitations of our AI-powered Instagram bio generator tool and related legal notices.",
  alternates: {
    canonical: "https://profilebiogenerator.site/disclaimer",
  },
  openGraph: {
    title: "Disclaimer | InstaBioGen",
    description: "Read InstaBioGen's disclaimer policies.",
    url: "https://profilebiogenerator.site/disclaimer",
    type: "website",
  },
  twitter: {
    card: "summary",
    title: "Disclaimer | InstaBioGen",
    description: "Read InstaBioGen's disclaimer.",
  },
}

const sections = [
  {
    title: "1. General Disclaimer",
    content:
      "The information and content provided on InstaBioGen (profilebiogenerator.site) is for general informational and entertainment purposes only. All content, including AI-generated Instagram bios, blog posts, and tips, is provided on an \"as is\" and \"as available\" basis without any warranties or guarantees of any kind, whether express or implied. We make no representations about the accuracy, reliability, completeness, or suitability of any information on this website for any particular purpose.",
  },
  {
    title: "2. No Affiliation with Instagram or Meta",
    content:
      "InstaBioGen is an independent third-party tool. We are NOT affiliated with, endorsed by, sponsored by, or in any way officially connected with Instagram, Meta Platforms Inc., Facebook, or any of their subsidiaries, partners, or affiliates. The name \"Instagram\" is used throughout our website solely for reference and descriptive purposes. All Instagram-related trademarks, logos, and brand names are the property of Meta Platforms Inc.",
  },
  {
    title: "3. AI-Generated Content Disclaimer",
    content:
      "Our Instagram bio generator uses algorithms and curated content libraries to create bio suggestions. While we strive to produce creative, engaging, and appropriate content, please understand the following:",
    list: [
      "Generated bios are algorithmic suggestions, not professional advice or endorsements.",
      "We cannot guarantee that every generated bio will be suitable for all audiences, contexts, or purposes.",
      "Some generated content may unintentionally resemble existing bios or copyrighted material.",
      "Users are solely responsible for reviewing, editing, and moderating bios before using them on their profiles.",
      "We recommend checking that your chosen bio complies with Instagram's Community Guidelines and Terms of Service.",
    ],
  },
  {
    title: "4. No Guarantee of Results",
    content:
      "Using bios generated by InstaBioGen does not guarantee any specific outcomes such as increased followers, higher engagement, profile visibility, or social media success. The effectiveness of any Instagram bio depends on many factors outside our control, including your content quality, posting consistency, niche, and Instagram's own algorithm.",
  },
  {
    title: "5. Limitation of Liability",
    content:
      "To the fullest extent permitted by applicable law, InstaBioGen and its creators, contributors, and affiliates shall not be held liable for any direct, indirect, incidental, consequential, special, or punitive damages arising from or related to:",
    list: [
      "Your use of or inability to use our website or bio generator tool.",
      "Any content generated by our tool that you choose to use on your social media profiles.",
      "Any actions taken by Instagram or other platforms in response to bios you use.",
      "Errors, inaccuracies, or omissions in our generated content or website information.",
      "Any unauthorized access to or alteration of your data or transmissions.",
      "Any loss of data, profits, goodwill, or other intangible losses.",
    ],
  },
  {
    title: "6. External Links Disclaimer",
    content:
      "Our website may contain links to external third-party websites or resources. These links are provided for convenience and informational purposes only. We have no control over the content, availability, privacy practices, or accuracy of external websites. Inclusion of any link does not imply endorsement or recommendation by InstaBioGen. You access external links entirely at your own risk.",
  },
  {
    title: "7. Blog & Educational Content",
    content:
      "The blog posts and articles on InstaBioGen are intended to provide helpful tips and inspiration related to Instagram bios and social media. This content represents our opinions and research at the time of writing and should not be treated as professional social media advice. Social media trends change rapidly, and information may become outdated.",
  },
  {
    title: "8. Accuracy of Information",
    content:
      "We make reasonable efforts to keep the information on this website accurate and up to date, but we do not warrant that all content is error-free, complete, or current. Statistics, user counts, and other figures mentioned on the website are approximate and may not reflect real-time data.",
  },
  {
    title: "9. Changes to This Disclaimer",
    content:
      "We reserve the right to modify, update, or replace any part of this disclaimer at any time without prior notice. Changes become effective immediately upon posting on this page. Your continued use of InstaBioGen after any changes constitutes acceptance of the updated disclaimer. We recommend reviewing this page periodically.",
  },
  {
    title: "10. Contact",
    content:
      "If you have any questions or concerns about this disclaimer, please reach out to us at contact@profilebiogenerator.site. We are happy to clarify anything.",
  },
]

export default function DisclaimerPage() {
  return (
    <>
      {/* Hero */}
      <section className="relative overflow-hidden bg-background py-16 lg:py-24">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,var(--tw-gradient-stops))] from-primary/5 via-transparent to-transparent" />
        <div className="relative mx-auto max-w-3xl px-4 lg:px-8">
          <div className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-1.5 text-sm font-medium text-primary">
            <AlertTriangle className="h-3.5 w-3.5" />
            Legal Notice
          </div>
          <h1
            className="mt-6 text-4xl font-bold tracking-tight text-foreground md:text-5xl"
            style={{ fontFamily: "var(--font-heading)" }}
          >
            Disclaimer
          </h1>
          <p className="mt-4 text-lg text-muted-foreground">
            Last updated: February 2026
          </p>
          <p className="mt-2 leading-relaxed text-muted-foreground">
            Please read this disclaimer carefully before using InstaBioGen.
            By accessing or using our website, you acknowledge that you have
            read, understood, and agree to be bound by the following terms.
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="border-t border-border bg-card py-16 lg:py-20">
        <div className="mx-auto max-w-3xl px-4 lg:px-8">
          <div className="flex flex-col gap-10">
            {sections.map((section) => (
              <div
                key={section.title}
                className="rounded-2xl border border-border bg-background p-6 md:p-8"
              >
                <h2 className="text-xl font-bold text-foreground">
                  {section.title}
                </h2>
                {section.content && (
                  <p className="mt-3 leading-relaxed text-muted-foreground">
                    {section.content}
                  </p>
                )}
                {section.list && (
                  <ul className="mt-4 flex flex-col gap-2 pl-1">
                    {section.list.map((item) => (
                      <li key={item} className="flex items-start gap-2">
                        <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-primary" />
                        <p className="text-sm leading-relaxed text-muted-foreground">
                          {item}
                        </p>
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>
    </>
  )
}
